{
 "title": "User Feedback",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Services",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT service, COUNT(service) FROM user_feedback GROUP BY service;"
    }
   ]
  },
  {
   "title": "Total Feedback Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM user_feedback;"
    }
   ]
  },
  {
   "title": "By Feedback Type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(feedback), feedback_type FROM user_feedback GROUP BY feedback, feedback_type; "
    }
   ]
  },
  {
   "title": "Category",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT category, COUNT(category) FROM user_feedback GROUP BY category;"
    }
   ]
  },
  {
   "title": "Avg Feedback Rating",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(feedback) FROM user_feedback;"
    }
   ]
  }
 ]
}